name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up developer environment
        run: |
          python -m pip install invoke poetry
          poetry install
      - name: Run pylint
        run: |
          invoke pylint
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up developer environment
        run: |
          python -m pip install invoke poetry
          poetry install
      - name: Run black
        run: |
          invoke black --check
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up developer environment
        run: |
          python -m pip install invoke poetry
          poetry install
      - name: Run mypy
        run: |
          invoke mypy
