name: release
  
on: workflow_dispatch

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: 
      name: PyPI
      url: https://pypi.org/project/sysx/
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Build sysx
        run: |
          python -m pip install build
          python -m build
      - name: Upload distribution archives
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_REPOSITORY: ${{ secrets.TWINE_REPOSITORY }}
        run: |
          python -m pip install twine
          python -m twine upload dist/*